server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/localhostdb?serverTimezone=CET
    username: root
    password: Vonhio123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Europe/Madrid
    date-format: yyyy-MM-dd HH:mm:ss
